---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(readr)
library(tidyverse)
library(plotrix)
```


```{r}
crime <- read_csv('/Users/wyattromero/Downloads/Crime-Rate-in-Denver/Crime.csv')
```

```{r}
dim(crime)
```

```{r}
str(crime)
```

```{r}
summary(crime)
```


```{r}
#Remove variables not in use for analysis
crime <- select(crime, c('incident_id', 'DISTRICT_ID'))
head(crime)
```

```{r}
#check for null values
crime[crime == "?"] <- NA
colSums(is.na(crime))

crime <- na.omit(crime)
```

```{r}
#check if null values were omitted
colSums(is.na(crime))
```

```{r}
write.csv(crime, "crime_capstone.csv", row.names = TRUE)
```


```{r}
graph <- ggplot(filter(crime), aes(fct_infreq(factor(DISTRICT_ID)))) + geom_bar()
graph
```

```{r}
as.data.frame(table(crime$DISTRICT_ID))
```


```{r}
slices <- c(56478, 50802, 78771, 45707, 39354, 83586, 5744)
labels <- c("D1", "D2", "D3", "D4", "D5", "D6", "D7")
percent <- round(slices/sum(slices)*100)
labels <- paste(labels, percent)
labels <- paste(labels, "%", sep="")
pie(slices, labels = labels, main = "Pie Chart of Crime", col=rainbow(length(labels)))
```

